module.exports = {
  // 物资筹备
  作战记录: { top: "supplies", episode: "tactical_drill", operation: "operation_ls_5", update: false, count: false },
  技巧概要: { top: "supplies", episode: "aerial_threat", operation: "operation_ca_5", update: false, count: false },
  采购凭证: { top: "supplies", episode: "tough_siege", operation: "operation_ap_5", update: false, count: false },
  龙门币: { top: "supplies", episode: "cargo_escort", operation: "operation_ce_5", update: false, count: false },
  // 芯片搜索
  重装芯片: { top: "chips", episode: "solid_defense", operation: "operation_pr_a_1", update: false, count: true },
  重装芯片组: { top: "chips", episode: "solid_defense", operation: "operation_pr_a_2", update: false, count: true },
  医疗芯片: { top: "chips", episode: "solid_defense", operation: "operation_pr_a_1", update: false, count: true },
  医疗芯片组: { top: "chips", episode: "solid_defense", operation: "operation_pr_a_2", update: false, count: true },
  狙击芯片: { top: "chips", episode: "fierce_attack", operation: "operation_pr_b_1", update: false, count: true },
  狙击芯片组: { top: "chips", episode: "fierce_attack", operation: "operation_pr_b_2", update: false, count: true },
  术师芯片: { top: "chips", episode: "fierce_attack", operation: "operation_pr_b_1", update: false, count: true },
  术师芯片组: { top: "chips", episode: "fierce_attack", operation: "operation_pr_b_2", update: false, count: true },
  先锋芯片: { top: "chips", episode: "unstoppable_charge", operation: "operation_pr_c_1", update: false, count: true },
  先锋芯片组: { top: "chips", episode: "unstoppable_charge", operation: "operation_pr_c_2", update: false, count: true },
  辅助芯片: { top: "chips", episode: "unstoppable_charge", operation: "operation_pr_c_1", update: false, count: true },
  辅助芯片组: { top: "chips", episode: "unstoppable_charge", operation: "operation_pr_c_2", update: false, count: true },
  近卫芯片: { top: "chips", episode: "fearless_protection", operation: "operation_pr_d_1", update: false, count: true },
  近卫芯片组: { top: "chips", episode: "fearless_protection", operation: "operation_pr_d_2", update: false, count: true },
  特种芯片: { top: "chips", episode: "fearless_protection", operation: "operation_pr_d_1", update: false, count: true },
  特种芯片组: { top: "chips", episode: "fearless_protection", operation: "operation_pr_d_2", update: false, count: true },
  // 剿灭模式
  合成玉: { top: "annihilation", operation: "lungmen_district", update: false, count: false },
  // 其他材料
  炽合金: {top: "main", episode: "episode_3", operation: "operation_3_7_4", update: true, count: true },
  固源岩: { top: "main", episode: "episode_1", operation: "operation_1_7", update: true, count: true },
  聚酸酯组: {top: "main", episode: "episode_7", operation: "operation_7_4", update: true, count: true },
  凝胶: {top: "main", episode: "episode_5", operation: "operation_5_9_3", update: true, count: true },
  扭转醇: { top: "main", episode: "episode_4", operation: "operation_4_4", update: true, count: true },
  轻锰矿: { top: "main", episode: "episode_7", operation: "operation_7_16", update: true, count: true },
  全新装置: { top: "main", episode: "episode_7", operation: "operation_7_15", update: true, count: true },
  RMA7012: { top: "main", episode: "episode_7", operation: "operation_7_10", update: true, count: true },
  糖组: {top: "main", episode: "episode_2", operation: "operation_2_5", update: true, count: true },
  酮凝集组: {top: "main", episode: "episode_3", operation: "operation_3_1", update: true, count: true },
  研磨石: {top: "main", episode: "episode_3", operation: "operation_3_3", update: true, count: true },
  异铁组: { top: "main", episode: "episode_4", operation: "operation_4_3_1", update: true, count: true },
  // 活动材料
  // 活动材料1: {},
  // 活动材料2: {},
  // 活动材料3: {},
};
